apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  ports:
    - name: kafka
      port: 9092
  selector:
    app: redpanda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
        command:
        - /usr/bin/rpk
        - redpanda
        - start
        - --overprovisioned
        - --smp=1
        - --memory=2G
        - --kafka-addr=0.0.0.0:9092
        ports:
        - containerPort: 9092
        resources:
          limits:
            memory: "2Gi"
        volumeMounts:
        - name: redpanda-storage
          mountPath: /var/lib/redpanda/data
      volumes:
      - name: redpanda-storage
        persistentVolumeClaim:
          claimName: redpanda-pvc