apiVersion: v1
kind: Secret
metadata:
  name: timescale-secret
type: Opaque
data:
  postgres-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi