apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: binance-kline-app
  namespace: airflow
spec:
  image: kdquangrepo/flink:1.18-custom-v3
  flinkVersion: v1_18
  flinkConfiguration:
    state.checkpoints.dir: gs://flink-checkpoints-1773848181/checkpoints
    execution.checkpointing.interval: "10s"
    execution.checkpointing.mode: "EXACTLY_ONCE"
    state.backend.type: hashmap
    
    google.cloud.auth.service.account.json.key.file: /etc/flink/gcp/gcs-key.json
    fs.gs.project.id: "datn-489915"
    high-availability.type: kubernetes
    high-availability.storageDir: gs://flink-checkpoints-1773848181/ha

  jobManager:
    resource: { memory: "1024m", cpu: 1 }
  taskManager:
    resource: { memory: "1024m", cpu: 1 }

  job:
    jarURI: local:///opt/flink/bin/sql-gateway.sh 
    args: ["/opt/flink/bin/sql-client.sh", "-f", "/opt/flink/sql/binance_job.sql"]
    parallelism: 1
    upgradeMode: last-state

  podTemplate:
    spec:
      serviceAccountName: flink-operator-sa
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: gcp-key-vol
              mountPath: /etc/flink/gcp
              readOnly: true
            - name: sql-file
              mountPath: /opt/flink/sql
      volumes:
        - name: gcp-key-vol
          secret: { secretName: gcs-key-secret }
        - name: sql-file
          configMap: { name: binance-sql-config }