apiVersion: v1
kind: Service
metadata:
  name: binance-flink-cluster-rest
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: binance-flink-cluster
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081