apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-metrics-monitor
  namespace: monitoring
  labels:
    # Label này cực kỳ quan trọng, nó giúp Prometheus Operator biết đây là file config dành cho nó
    release: monitoring 
spec:
  namespaceSelector:
    matchNames:
      - airflow # Trỏ về namespace chứa Flink của bạn
  selector:
    matchLabels:
      app: binance-kline-job # Tên deployment của Flink
  podMetricsEndpoints:
  - targetPort: 9249
    path: /
    interval: 15s