apiVersion: v1
kind: Service
metadata:
  name: flink-metrics
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: binance-kline-job
  ports:
    - port: 9249
      targetPort: 9249
      nodePort: 30949