apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: binance-flink-cluster
  namespace: airflow
spec:
  image: khongducquang/flink:1.18-custom-v2
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    jobmanager.memory.process.size: "1000m"
    taskmanager.memory.process.size: "2000m"
    resourcemanager.taskmanager-timeout: "30000"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1G"  
      cpu: 0.5     
  taskManager:
    replicas: 1       
    resource:
      memory: "2G"  
      cpu: 0.5