executor: "LocalExecutor"

postgresql:
  enabled: true

webserver:
  enabled: true
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30080

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/KhongDucQuang/FinancialDataPlatform.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    wait: 30
    subPath: "src/dags"
  persistence:
    enabled: false

# Tắt các thành phần thừa để dồn RAM cho Spark sau này
redis: {enabled: false}
flower: {enabled: false}
statsd: {enabled: false}