apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-producer
  template:
    metadata:
      labels:
        app: binance-producer
    spec:
      containers:
      - name: producer
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e 
            
            echo "--- Installing dependencies ---"
            pip install --no-cache-dir binance-connector kafka-python
            
            echo "--- Downloading code from GitHub ---"
            apt-get update && apt-get install -y curl
            curl -sSL https://raw.githubusercontent.com/KhongDucQuang/FinancialDataPlatform/main/src/producers/binance_producer.py -o binance_producer.py
            
            echo "--- Starting the Bot ---"
            python -u binance_producer.py
        env:
        - name: KAFKA_SERVER
          value: "redpanda:9092"
        - name: PYTHONUNBUFFERED
          value: "1"