apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  ports:
    - port: 5432
      nodePort: 30432
  selector:
    app: timescaledb
  type: NodePort 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescale
        image: timescale/timescaledb:latest-pg15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescale-secret
              key: postgres-password
        resources:
          limits:
            memory: "3Gi" # Bạn có 16GB nên 3GB cho DB là rất thoải mái
            cpu: "1"
        volumeMounts:
        - name: timescale-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: timescale-storage
        persistentVolumeClaim:
          claimName: timescale-pvc